// This file was automatically generated by friendly type erasure.
// Please do not modify.

#pragma once

#include <functional>
#include <Spacy/vector.hh>

namespace Spacy
{
    namespace IndefiniteLinearSolverDetail
    {
        template < class Interface >
        struct Functions
        {
            using delete_function = void ( * )( void* );
            using clone_function = void* (*)( void* );
            using call_const_Vector__ref__function = Vector ( * )( const Interface&, void*, const Vector& x );
            using isPositiveDefinite_function = bool ( * )( const Interface&, void* );

            delete_function del;
            clone_function clone;
            call_const_Vector__ref__function call_const_Vector__ref_;
            isPositiveDefinite_function isPositiveDefinite;
        };

        template < class Interface, class Impl >
        struct execution_wrapper
        {
            static Vector call_const_Vector__ref_( const Interface& interface, void* impl, const Vector& x )
            {
                return static_cast< const Impl* >( impl )->operator()( x );
            }

            static bool isPositiveDefinite( const Interface& interface, void* impl )
            {
                return static_cast< const Impl* >( impl )->isPositiveDefinite();
            }
        };

        template < class Interface, class Impl >
        struct execution_wrapper< Interface, std::reference_wrapper< Impl > >
        {
            static Vector call_const_Vector__ref_( const Interface& interface, void* impl, const Vector& x )
            {
                return static_cast< std::reference_wrapper< Impl >* >( impl )->get().operator()( x );
            }

            static bool isPositiveDefinite( const Interface& interface, void* impl )
            {
                return static_cast< std::reference_wrapper< Impl >* >( impl )->get().isPositiveDefinite();
            }
        };
    }
}
