#!/bin/bash

python2 /home/lars/Projects/type_erasure/emtypen/emtypen.py --form /home/lars/Projects/type_erasure/emtypen/forms/sbo_cow.hpp --headers /home/lars/Projects/type_erasure/emtypen/headers/sbo_cow.hpp --copy-on-write True --clang-path /usr/lib/llvm-3.8/lib plain_interface.hh > interface.hh
