#!/bin/bash

UTIL_DIR=Spacy/Util
DETAIL_DIR=Detail
BUFFER_SIZE=16
INCLUDE_DIR=/home/lars/Projects/Spacy

COMMAND=/home/lars/Libraries/build-llvm2/bin/clang-type-erase
COMMON_ARGS="-detail-dir=$DETAIL_DIR -include-dir=$INCLUDE_DIR -util-dir=$UTIL_DIR -util-include-dir=<$UTIL_DIR/type_erasure_util.h> -storage-include-dir=<$UTIL_DIR/storage.h>"
SMALL_SBO_ARGS="-sbo -buffer-size=$BUFFER_SIZE"

function generate_interface {
echo "generate $1"
$COMMAND $COMMON_ARGS $2 -target-dir=Spacy $1 -std=c++14
}

function generate_interfaces {
generate_interface zeroVectorCreator.hh ""
generate_interface          operator.hh "$SMALL_SBO_ARGS"
generate_interface    linearOperator.hh "$SMALL_SBO_ARGS"
generate_interface        c1Operator.hh "$SMALL_SBO_ARGS"
generate_interface   dynamicOperator.hh "$SMALL_SBO_ARGS"
generate_interface        functional.hh "$SMALL_SBO_ARGS"
generate_interface      c1Functional.hh "$SMALL_SBO_ARGS"
generate_interface      c2Functional.hh "$SMALL_SBO_ARGS"
generate_interface            vector.hh "$SMALL_SBO_ARGS"
generate_interface linearSolver.hh ""
}

mkdir -p $INCLUDE_DIR/Spacy/$DETAIL_DIR
generate_interfaces

# generate interface for conjugate gradient methods
echo "for CG: generate terminationCriterion.hh"
CG_DIR=Spacy/Algorithm/CG
mkdir -p $INCLUDE_DIR/$CG_DIR/$DETAIL_DIR
$COMMAND $COMMON_ARGS -target-dir=$CG_DIR terminationCriterion.hh -std=c++14
$COMMAND $COMMON_ARGS -target-dir=$CG_DIR Regularization.hh -std=c++14

# generate interface for printer of logger
echo "for logger: generate printer.hh"
mkdir -p $INCLUDE_DIR/$UTIL_DIR/$DETAIL_DIR
$COMMAND $COMMON_ARGS -target-dir=$UTIL_DIR printer.hh -std=c++14

