// This file was automatically generated by friendly type erasure.
// Please do not modify.

#pragma once

#include <array>
#include <Spacy/Spaces/RealSpace/real.hh>
#include <Spacy/vector.hh>
#include <Spacy/vectorSpace.hh>
#include "Detail/details_for_c1Functional.hh"
#include "Util/table_util.hh"

namespace Spacy
{
    /// Type-erased differentiable functional \f$f:\ X \to \mathbb{R} \f$.
    class C1Functional
    {
    public:
        C1Functional() noexcept;

        template < typename T, typename std::enable_if< !std::is_same<
                                   C1Functional, typename std::decay< T >::type >::value >::type* = nullptr >
        C1Functional( T&& value )
            : functions_(
                  {&type_erasure_table_detail::clone_into_shared_ptr< typename std::decay< T >::type >,
                   &type_erasure_table_detail::clone_into_buffer< typename std::decay< T >::type, Buffer >,
                   &C1FunctionalDetail::execution_wrapper< C1Functional,
                                                           typename std::decay< T >::type >::call_const_Vector__ref_,
                   &C1FunctionalDetail::execution_wrapper< C1Functional, typename std::decay< T >::type >::d1,
                   &C1FunctionalDetail::execution_wrapper< C1Functional, typename std::decay< T >::type >::domain} ),
              type_id_( typeid( typename std::decay< T >::type ).hash_code() ), impl_( nullptr )
        {
            if ( sizeof( typename std::decay< T >::type ) <= sizeof( Buffer ) )
            {
                new ( &buffer_ ) typename std::decay< T >::type( std::forward< T >( value ) );
                impl_ = std::shared_ptr< typename std::decay< T >::type >(
                    std::shared_ptr< typename std::decay< T >::type >(),
                    static_cast< typename std::decay< T >::type* >( static_cast< void* >( &buffer_ ) ) );
            }
            else
                impl_ = std::make_shared< typename std::decay< T >::type >( std::forward< T >( value ) );
        }

        C1Functional( const C1Functional& other );

        C1Functional( C1Functional&& other ) noexcept;

        template < typename T, typename std::enable_if< !std::is_same<
                                   C1Functional, typename std::decay< T >::type >::value >::type* = nullptr >
        C1Functional& operator=( T&& value )
        {
            return *this = C1Functional( std::forward< T >( value ) );
        }

        C1Functional& operator=( const C1Functional& other );

        C1Functional& operator=( C1Functional&& other ) noexcept;

        /**
         * @brief Checks if the type-erased interface holds an implementation.
         * @return true if an implementation is stored, else false
         */
        explicit operator bool() const noexcept;

        /// Apply functional.
        Real operator()( const Vector& x ) const;

        /// Compute derivative as function space element in \f$X^*\f$, where \f$x\in X\f$.
        Vector d1( const Vector& x ) const;

        /// Access domain space \f$X\f$.
        const VectorSpace& domain() const;

        /**
        * @brief Conversion of the stored implementation to @code  T* @endcode.
        * @return pointer to the stored object if conversion was successful, else nullptr
        */
        template < class T >
        T* target() noexcept
        {
            return type_erasure_table_detail::dynamic_cast_impl< T >( type_id_, read() );
        }

        /**
        * @brief Conversion of the stored implementation to @code const T* @endcode.
        * @return pointer to the stored object if conversion was successful, else nullptr
        */
        template < class T >
        const T* target() const noexcept
        {
            return type_erasure_table_detail::dynamic_cast_impl< T >( type_id_, read() );
        }

    private:
        using Buffer = std::array< char, 64 >;

        void* read() const noexcept;

        void* write();

        C1FunctionalDetail::Functions< C1Functional, Buffer > functions_;
        std::size_t type_id_;
        std::shared_ptr< void > impl_ = nullptr;
        Buffer buffer_;
    };
}
