// This file was automatically generated by friendly type erasure.
// Please do not modify.

#pragma once

#include <array>
#include "Spacy/Util/table_util.hh"
#include <Spacy/linearOperator.hh>
#include <Spacy/vector.hh>
#include <Spacy/vectorSpace.hh>
#include "Detail/details_for_c1Operator.hh"

namespace Spacy
{
    /// Type-erased differentiable operator \f$A:\ X \to Y \f$.
    class C1Operator
    {
    public:
        C1Operator() noexcept;

        template < typename T, typename std::enable_if< C1OperatorDetail::C1OperatorConcept<
                                   C1Operator, typename std::decay< T >::type >::value >::type* = nullptr >
        C1Operator( T&& value )
            : functions_(
                  {&type_erasure_table_detail::clone_into_shared_ptr< typename std::decay< T >::type >,
                   &type_erasure_table_detail::clone_into_buffer< typename std::decay< T >::type, Buffer >,
                   &C1OperatorDetail::execution_wrapper< C1Operator,
                                                         typename std::decay< T >::type >::call_const_Vector_ref,
                   &C1OperatorDetail::execution_wrapper< C1Operator, typename std::decay< T >::type >::d1,
                   &C1OperatorDetail::execution_wrapper< C1Operator, typename std::decay< T >::type >::linearization,
                   &C1OperatorDetail::execution_wrapper< C1Operator, typename std::decay< T >::type >::domain,
                   &C1OperatorDetail::execution_wrapper< C1Operator, typename std::decay< T >::type >::range} ),
              type_id_( typeid( typename std::decay< T >::type ).hash_code() ), impl_( nullptr )
        {
            if ( sizeof( typename std::decay< T >::type ) <= sizeof( Buffer ) )
            {
                new ( &buffer_ ) typename std::decay< T >::type( std::forward< T >( value ) );
                impl_ = std::shared_ptr< typename std::decay< T >::type >(
                    std::shared_ptr< typename std::decay< T >::type >(),
                    static_cast< typename std::decay< T >::type* >( static_cast< void* >( &buffer_ ) ) );
            }
            else
                impl_ = std::make_shared< typename std::decay< T >::type >( std::forward< T >( value ) );
        }

        C1Operator( const C1Operator& other );

        C1Operator( C1Operator&& other ) noexcept;

        template < typename T, typename std::enable_if< C1OperatorDetail::C1OperatorConcept<
                                   C1Operator, typename std::decay< T >::type >::value >::type* = nullptr >
        C1Operator& operator=( T&& value )
        {
            return *this = C1Operator( std::forward< T >( value ) );
        }

        C1Operator& operator=( const C1Operator& other );

        C1Operator& operator=( C1Operator&& other ) noexcept;

        /**
         * @brief Checks if the type-erased interface holds an implementation.
         * @return true if an implementation is stored, else false
         */
        explicit operator bool() const noexcept;

        /// Apply operator.
        Vector operator()( const Vector& x ) const;

        /// Compute directional derivative \f$A'(x)\delta x\f$.
        Vector d1( const Vector& x, const Vector& dx ) const;

        /// Get linearization \f$A'(x):\ X\to Y \f$
        LinearOperator linearization( const Vector& x ) const;

        /// Access domain space \f$X\f$.
        const VectorSpace& domain() const;

        /// Access range space \f$Y\f$.
        const VectorSpace& range() const;

        /**
        * @brief Conversion of the stored implementation to @code  T* @endcode.
        * @return pointer to the stored object if conversion was successful, else nullptr
        */
        template < class T >
        T* target() noexcept
        {
            return type_erasure_table_detail::dynamic_cast_impl< T >( type_id_, read() );
        }

        /**
        * @brief Conversion of the stored implementation to @code const T* @endcode.
        * @return pointer to the stored object if conversion was successful, else nullptr
        */
        template < class T >
        const T* target() const noexcept
        {
            return type_erasure_table_detail::dynamic_cast_impl< T >( type_id_, read() );
        }

    private:
        using Buffer = std::array< char, 64 >;

        void* read() const noexcept;

        void* write();

        C1OperatorDetail::Functions< C1Operator, Buffer > functions_;
        std::size_t type_id_;
        std::shared_ptr< void > impl_ = nullptr;
        Buffer buffer_;
    };

    /**
    * @brief For an operator \f$ A: X\to Y \f$, compute \f$A'\f$ at \f$x\in X\f$ as linear operator \f$ A'(x): X \to Y
    * \f$.
    *
    * Equivalent to calling A.linearization(x).
    *
    * @param A differentiable operator
    * @param x point of linearization
    * @return \f$A'(x)\f$, i.e. A.linearization(x).
    * @see @ref C1OperatorAnchor "C1Operator", @ref LinearOperatorAnchor "LinearOperator"
    */
    LinearOperator d1( const C1Operator& A, const Vector& x );
}
