// This file was automatically generated by friendly type erasure.
// Please do not modify.

#include "functional.hh"

namespace Spacy
{
    Functional::Functional() noexcept : impl_( nullptr )
    {
    }

    Functional::Functional( const Functional& other )
        : functions_( other.functions_ ), type_id_( other.type_id_ ), impl_( other.impl_ )
    {
    }

    Functional::Functional( Functional&& other ) noexcept : functions_( other.functions_ ), type_id_( other.type_id_ )
    {
        if ( type_erasure_table_detail::is_heap_allocated( other.impl_.get(), other.buffer_ ) )
            impl_ = std::move( other.impl_ );
        else
            other.functions_.clone_into( other.impl_.get(), buffer_, impl_ );
        other.impl_ = nullptr;
    }

    Functional& Functional::operator=( const Functional& other )
    {
        functions_ = other.functions_;
        type_id_ = other.type_id_;
        impl_ = other.impl_;
        return *this;
    }

    Functional& Functional::operator=( Functional&& other ) noexcept
    {
        type_id_ = other.type_id_;
        functions_ = other.functions_;
        if ( type_erasure_table_detail::is_heap_allocated( other.impl_.get(), other.buffer_ ) )
            impl_ = std::move( other.impl_ );
        else
            other.functions_.clone_into( other.impl_.get(), buffer_, impl_ );
        other.impl_ = nullptr;
        return *this;
    }

    Functional::operator bool() const noexcept
    {
        return impl_ != nullptr;
    }

    Real Functional::operator()( const Vector& x ) const
    {
        assert( impl_ );
        return functions_.call_const_Vector_ref( *this, read(), x );
    }

    const VectorSpace& Functional::domain() const
    {
        assert( impl_ );
        return functions_.domain( *this, read() );
    }

    void* Functional::read() const noexcept
    {
        assert( impl_ );
        return impl_.get();
    }

    void* Functional::write()
    {
        if ( !impl_.unique() )
        {
            if ( type_erasure_table_detail::is_heap_allocated( impl_.get(), buffer_ ) )
                functions_.clone( impl_.get(), impl_ );
            else
                functions_.clone_into( impl_.get(), buffer_, impl_ );
        }
        return impl_.get();
    }
}
